### PR TITLE
Add a pattern parameter to filter out files

### PR DESCRIPTION
**Pull request by tyoshino**

### CODE REVIEW

**Comment by tyoshino** [comment]
I'd like to run only specified files. I'm not sure if it's better to use glob or regex. Wanna hear your opinion, domenic.

**Comment by domenic** [comment]
Hmm. I think glob would be best because then it's idiomatic in the CLI interface as well. Or maybe just a function for filtering in the API, and the CLI accepts a glob and passes in a function that does glob filtering?

**Comment by tyoshino** [comment]
Changed to use glob. Chromium's layout test running script also uses glob ( https://codesearch.chromium.org/chromium/src/third_party/WebKit/Tools/Scripts/webkitpy/common/find_files.py ). I checked the code and tried to imitate its behavior. It takes a list of glob patterns, expands each of them and concatenates the resulting lists of files. I and @ricea has been feeling that the behavior is convenient, so I'd like to implement it if it's ok.

**Comment by tyoshino** [comment]
> Or maybe just a function for filtering in the API,

Thanks. But it seems the code will be simpler without this. PTAL.

**Comment by domenic** [comment]
I went with the filter function approach. It ends up being a lot less code on both sides :).

**Pull request closed without merging**
